apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    appconnectenterprise: operator-icp4i
    deployment.kubernetes.io/revision: '2'
    serverName: anas-server-11
  creationTimestamp: '2022-06-28T07:47:57Z'
  generation: 249
  labels:
    app.kubernetes.io/instance: anas-server-11
    app.kubernetes.io/managed-by: ibm-appconnect
    app.kubernetes.io/name: anas-server-11
    appconnect.ibm.com/kind: IntegrationServer
    release: anas-server-11
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:appconnectenterprise': {}
            'f:serverName': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/managed-by': {}
            'f:app.kubernetes.io/name': {}
            'f:appconnect.ibm.com/kind': {}
            'f:release': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"157cfafb-507c-44fd-a059-09d827458739"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:annotations':
                .: {}
                'f:cloudpakId': {}
                'f:cloudpakName': {}
                'f:productChargedContainers': {}
                'f:productCloudpakRatio': {}
                'f:productID': {}
                'f:productMetric': {}
                'f:productName': {}
              'f:labels':
                .: {}
                'f:app.kubernetes.io/instance': {}
                'f:app.kubernetes.io/managed-by': {}
                'f:app.kubernetes.io/name': {}
                'f:appconnect.ibm.com/kind': {}
                'f:release': {}
            'f:spec':
              'f:affinity':
                .: {}
                'f:nodeAffinity':
                  .: {}
                  'f:requiredDuringSchedulingIgnoredDuringExecution':
                    .: {}
                    'f:nodeSelectorTerms': {}
                'f:podAntiAffinity':
                  .: {}
                  'f:preferredDuringSchedulingIgnoredDuringExecution': {}
              'f:containers':
                'k:{"name":"anas-server-11"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"ACE_ADMIN_SERVER_CA"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ADMIN_SERVER_CERT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ADMIN_SERVER_KEY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ADMIN_SERVER_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ADMIN_SERVER_SECURITY"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_CONFIGURATIONS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_DEFAULT_APPLICATION_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ENABLE_METRICS"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_ENABLE_OPEN_TRACING"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"ACE_SERVER_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"APP_CONNECT_LICENSE_TOGGLES"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DEFAULT_CONTENT_SERVER"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"DESIGNER_FLOWS_OPERATION_MODE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"GODEBUG"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LICENSE"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"LOG_FORMAT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MQSI_OVERRIDE_HOSTNAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MQSI_OVERRIDE_HTTP_PORT"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SERVICE_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:image': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":7600,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":7800,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                    'k:{"containerPort":7843,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:name': {}
                      'f:protocol': {}
                  'f:readinessProbe':
                    .: {}
                    'f:exec':
                      .: {}
                      'f:command': {}
                    'f:failureThreshold': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:ephemeral-storage': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:ephemeral-storage': {}
                      'f:memory': {}
                  'f:securityContext':
                    .: {}
                    'f:allowPrivilegeEscalation': {}
                    'f:capabilities':
                      .: {}
                      'f:drop': {}
                    'f:privileged': {}
                    'f:readOnlyRootFilesystem': {}
                    'f:runAsNonRoot': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"/home/aceuser/ace-server"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/home/aceuser/initial-config/webusers"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"/home/aceuser/secrets/anas-server-11-is-adminssl"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                      'f:readOnly': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:serviceAccount': {}
              'f:serviceAccountName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:volumes':
                .: {}
                'k:{"name":"ace-secret-0"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                    'f:secretName': {}
                'k:{"name":"webusers"}':
                  .: {}
                  'f:name': {}
                  'f:secret':
                    .: {}
                    'f:defaultMode': {}
                    'f:items': {}
                    'f:secretName': {}
                'k:{"name":"workdir"}':
                  .: {}
                  'f:emptyDir': {}
                  'f:name': {}
      manager: manager
      operation: Update
      time: '2022-06-28T07:47:57Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:unavailableReplicas': {}
          'f:updatedReplicas': {}
      manager: kube-controller-manager
      operation: Update
      time: '2022-06-28T08:31:05Z'
  name: anas-server-11-is
  namespace: poc-argocd
  ownerReferences:
    - apiVersion: appconnect.ibm.com/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: IntegrationServer
      name: anas-server-11
      uid: 157cfafb-507c-44fd-a059-09d827458739
  resourceVersion: '119269580'
  uid: d3be8130-5f6f-4ecb-a2ce-2d9de731862d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: anas-server-11
      app.kubernetes.io/managed-by: ibm-appconnect
      app.kubernetes.io/name: anas-server-11
      release: anas-server-11
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cloudpakId: c8b82d189e7545f0892db9ef2731b90d
        cloudpakName: IBM Cloud Pak for Integration
        productChargedContainers: anas-server-11
        productCloudpakRatio: '2:3'
        productID: eb5b5e73f62b4dcf8c434c6274a158a7
        productMetric: VIRTUAL_PROCESSOR_CORE
        productName: IBM App Connect Enterprise for non-production
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: anas-server-11
        app.kubernetes.io/managed-by: ibm-appconnect
        app.kubernetes.io/name: anas-server-11
        appconnect.ibm.com/kind: IntegrationServer
        release: anas-server-11
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - s390x
                      - ppc64le
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: anas-server-11
                    app.kubernetes.io/managed-by: ibm-appconnect
                    app.kubernetes.io/name: anas-server-11
                    release: anas-server-11
                topologyKey: kubernetes.io/hostname
              weight: 100
      containers:
        - env:
            - name: ACE_DEFAULT_APPLICATION_NAME
              value: DefaultApplication
            - name: ACE_ENABLE_METRICS
              value: 'true'
            - name: ACE_ENABLE_OPEN_TRACING
              value: 'false'
            - name: ACE_SERVER_NAME
              value: anas-server-11
            - name: DESIGNER_FLOWS_OPERATION_MODE
              value: disabled
            - name: LOG_FORMAT
              value: basic
            - name: SERVICE_NAME
              value: anas-server-11-is
            - name: LICENSE
              value: accept
            - name: APP_CONNECT_LICENSE_TOGGLES
              value: '{"connector-ibmrpa":1}'
            - name: MQSI_OVERRIDE_HOSTNAME
              value: >-
                anas-server-11-http-poc-argocd.jbs-poc-wdc04-c3c-32x64-0abe335159b03c3875b36f776cdd6d65-0000.us-east.containers.appdomain.cloud
            - name: MQSI_OVERRIDE_HTTP_PORT
              value: '80'
            - name: GODEBUG
              value: x509ignoreCN=0
            - name: ACE_ADMIN_SERVER_SECURITY
              value: 'true'
            - name: ACE_ADMIN_SERVER_CA
              value: /home/aceuser/adminssl
            - name: ACE_ADMIN_SERVER_CERT
              value: /home/aceuser/adminssl/tls.crt.pem
            - name: ACE_ADMIN_SERVER_KEY
              value: /home/aceuser/adminssl/tls.key.pem
            - name: ACE_ADMIN_SERVER_NAME
              value: anas-server-11
            - name: ACE_CONFIGURATIONS
              value: anas-server-11-is-adminssl
            - name: DEFAULT_CONTENT_SERVER
              value: 'true'
          image: >-
            image-registry.openshift-image-registry.svc:5000/poc-sample-service/ace-service:1.1
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - chkacehealthy
            failureThreshold: 1
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: anas-server-11
          ports:
            - containerPort: 7600
              name: webui
              protocol: TCP
            - containerPort: 7800
              name: ace-http
              protocol: TCP
            - containerPort: 7843
              name: ace-https
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - chkacehealthy
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            limits:
              cpu: '1'
              ephemeral-storage: 20Gi
              memory: 1Gi
            requests:
              cpu: 200m
              ephemeral-storage: 5Gi
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/aceuser/initial-config/webusers
              name: webusers
            - mountPath: /home/aceuser/secrets/anas-server-11-is-adminssl
              name: ace-secret-0
              readOnly: true
            - mountPath: /home/aceuser/ace-server
              name: workdir
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: anas-server-11-is
      serviceAccountName: anas-server-11-is
      terminationGracePeriodSeconds: 30
      volumes:
        - name: webusers
          secret:
            defaultMode: 420
            items:
              - key: adminusers
                path: admin-users.txt
              - key: operatorusers
                path: operator-users.txt
              - key: viewerusers
                path: viewer-users.txt
              - key: editorusers
                path: editor-users.txt
              - key: auditusers
                path: audit-users.txt
            secretName: anas-server-11-is
        - name: ace-secret-0
          secret:
            defaultMode: 420
            items:
              - key: configuration
                path: configuration
            secretName: anas-server-11-is-adminssl
        - emptyDir: {}
          name: workdir
status:
  conditions:
    - lastTransitionTime: '2022-06-28T07:47:57Z'
      lastUpdateTime: '2022-06-28T07:47:57Z'
      message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: 'False'
      type: Available
    - lastTransitionTime: '2022-06-28T08:26:27Z'
      lastUpdateTime: '2022-06-28T08:26:27Z'
      message: ReplicaSet "anas-server-11-is-85fd55bdd5" is progressing.
      reason: ReplicaSetUpdated
      status: 'True'
      type: Progressing
  observedGeneration: 249
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
