--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ace-server-service
spec: 
  replicas: 2
  revisionHistoryLimit: 0
  selector: 
    matchLabels: 
      app: ace-server-service
  template: 
    metadata: 
      labels: 
        app: ace-server-service
    spec: 
      containers: 
        - 
          env: 
            - 
              name: LICENSE_LICENSE
              value: L-KSBM-C87FU2
            - 
              name: LICENSE_USE
              value: CloudPakForIntegrationNonProduction
            - 
              name: OPERAND_VERSION
              value: 12.0.2.0-r2
            - 
              name: LICENSE
              value: accept
          image: "image-registry.openshift-image-registry.svc:5000/poc-sample-service/ace-service:1.1"
          name: ace-server-argocd
          ports: 
            - 
              containerPort: 7600
              name: webui
              protocol: TCP
            - 
              containerPort: 7800
              name: ace-http
              protocol: TCP
            - 
              containerPort: 7843
              name: ace-https
              protocol: TCP