apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: anas-server-11
  namespace: poc-argocd
spec:
  pod:
   containers:
     runtime:
       image: image-registry.openshift-image-registry.svc:5000/poc-sample-service/ace-service:1.1
       imagePullPolicy: Always
  configurations: []
  designerFlowsOperationMode: disabled
  createDashboardUsers: true
  adminServerSecure: true
  license:
    accept: true
    license: L-APEH-C49KZH
    use: CloudPakForIntegrationNonProduction
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  useCommonServices: true
  #tracing:
  #  enabled: true
  #  namespace: tracing
  version: 12.0.2.0-r1