apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: poc-sample-service
resources:
- anas-server.yaml
- ace-server-dep.yaml
images: 
- name: image-registry.openshift-image-registry.svc:5000/poc-sample-service/ace-service
  newTag: "3.0"